<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExtraProductSeeder extends Seeder
{
    public function run(): void
    {
        $desc = 'Une fragrance exclusivement conçue pour sublimer votre personnalité. Notes boisées, florales et orientales se marient avec élégance pour un sillage inoubliable.';
        $ingr = 'Alcohol Denat., Aqua, Parfum (Fragrance), Benzyl Salicylate, Linalool, Limonene, Coumarin, Citronellol, Geraniol.';

        DB::table('products')->insert([

            // ── 10 BEST SELLERS (is_featured = true) — IDs 21–30 ─────────────
            [
                'id' => 21, 'brand_id' => 2, 'category_id' => 7,
                'name' => 'Bleu Intense Cologne',    'slug' => 'bleu-intense-cologne',
                'subtitle' => 'Cologne Fraîche Signature',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 320.00, 'original_price' => 420.00,
                'stock' => 40, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 22, 'brand_id' => 3, 'category_id' => 8,
                'name' => 'Sauvage Frais EDT',       'slug' => 'sauvage-frais-edt',
                'subtitle' => 'Eau de Toilette Intense',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 290.00, 'original_price' => null,
                'stock' => 35, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 23, 'brand_id' => 4, 'category_id' => 9,
                'name' => 'Ôde Rose Nuit',           'slug' => 'ode-rose-nuit',
                'subtitle' => 'Parfum de Nuit Floral',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 275.00, 'original_price' => 360.00,
                'stock' => 30, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 24, 'brand_id' => 5, 'category_id' => 10,
                'name' => 'Luna Rossa Gift Set',     'slug' => 'luna-rossa-gift-set',
                'subtitle' => 'Coffret Cadeau Luxe',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 450.00, 'original_price' => 580.00,
                'stock' => 20, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 25, 'brand_id' => 6, 'category_id' => 7,
                'name' => 'Gentleman Cologne',       'slug' => 'gentleman-cologne',
                'subtitle' => 'Cologne Élégant',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 255.00, 'original_price' => null,
                'stock' => 45, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 26, 'brand_id' => 7, 'category_id' => 8,
                'name' => 'Crystal Noir EDT',        'slug' => 'crystal-noir-edt',
                'subtitle' => 'Eau de Toilette Oriental',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 210.00, 'original_price' => 270.00,
                'stock' => 38, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 27, 'brand_id' => 8, 'category_id' => 11,
                'name' => 'Dahlia Rose Oil',         'slug' => 'dahlia-rose-oil',
                'subtitle' => 'Huile Parfumée Précieuse',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 185.00, 'original_price' => null,
                'stock' => 50, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 28, 'brand_id' => 1, 'category_id' => 9,
                'name' => 'Minuit Doré',             'slug' => 'minuit-dore',
                'subtitle' => 'Parfum de Nuit Boisé',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 265.00, 'original_price' => 330.00,
                'stock' => 28, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 29, 'brand_id' => 2, 'category_id' => 5,
                'name' => 'Chance Brume',            'slug' => 'chance-brume',
                'subtitle' => 'Brume Parfumée Légère',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 195.00, 'original_price' => 250.00,
                'stock' => 55, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 30, 'brand_id' => 3, 'category_id' => 4,
                'name' => "Rose N'Roses EDP",        'slug' => 'rose-nroses-edp',
                'subtitle' => 'Eau de Parfum Floral',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 340.00, 'original_price' => null,
                'stock' => 22, 'is_active' => true, 'is_featured' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // ── 30 REGULAR PRODUCTS — IDs 31–60 ──────────────────────────────
            // Category 7 — Cologne (5 products)
            [
                'id' => 31, 'brand_id' => 1, 'category_id' => 7,
                'name' => 'Aqua Bloom Cologne',      'slug' => 'aqua-bloom-cologne',
                'subtitle' => 'Cologne Aquatique',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 145.00, 'original_price' => 190.00,
                'stock' => 80, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 32, 'brand_id' => 4, 'category_id' => 7,
                'name' => 'Poème Absolu Cologne',    'slug' => 'poeme-absolu-cologne',
                'subtitle' => 'Cologne Floral Poétique',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 165.00, 'original_price' => null,
                'stock' => 60, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 33, 'brand_id' => 5, 'category_id' => 7,
                'name' => 'Amber Code Cologne',      'slug' => 'amber-code-cologne',
                'subtitle' => 'Cologne Oriental Ambré',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 190.00, 'original_price' => 240.00,
                'stock' => 45, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 34, 'brand_id' => 7, 'category_id' => 7,
                'name' => 'Versus Cologne',          'slug' => 'versus-cologne',
                'subtitle' => 'Cologne Frais & Épicé',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 175.00, 'original_price' => 220.00,
                'stock' => 55, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 35, 'brand_id' => 8, 'category_id' => 7,
                'name' => 'Pi Cologne',              'slug' => 'pi-cologne',
                'subtitle' => 'Cologne Boisé Chypré',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 160.00, 'original_price' => null,
                'stock' => 40, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Category 8 — Eau de Toilette (5 products)
            [
                'id' => 36, 'brand_id' => 1, 'category_id' => 8,
                'name' => 'Garden Dew EDT',          'slug' => 'garden-dew-edt',
                'subtitle' => 'Eau de Toilette Florale',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 130.00, 'original_price' => 170.00,
                'stock' => 75, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 37, 'brand_id' => 4, 'category_id' => 8,
                'name' => 'Hypnôse EDT',             'slug' => 'hypnose-edt',
                'subtitle' => 'Eau de Toilette Envoûtante',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 220.00, 'original_price' => 280.00,
                'stock' => 30, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 38, 'brand_id' => 5, 'category_id' => 8,
                'name' => "Infusion d'Iris EDT",     'slug' => 'infusion-diris-edt',
                'subtitle' => 'Eau de Toilette Poudré',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 240.00, 'original_price' => null,
                'stock' => 25, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 39, 'brand_id' => 6, 'category_id' => 8,
                'name' => 'Opium EDT',               'slug' => 'opium-edt',
                'subtitle' => 'Eau de Toilette Oriental',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 195.00, 'original_price' => 250.00,
                'stock' => 35, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 40, 'brand_id' => 7, 'category_id' => 8,
                'name' => 'Dylan Blue EDT',          'slug' => 'dylan-blue-edt',
                'subtitle' => 'Eau de Toilette Aquatique',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 210.00, 'original_price' => null,
                'stock' => 28, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Category 9 — Parfum de Nuit (5 products)
            [
                'id' => 41, 'brand_id' => 1, 'category_id' => 9,
                'name' => 'Rose Noire Nuit',         'slug' => 'rose-noire-nuit',
                'subtitle' => 'Parfum de Nuit Floral',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 235.00, 'original_price' => 310.00,
                'stock' => 32, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 42, 'brand_id' => 1, 'category_id' => 9,
                'name' => 'Oud Sombre Nuit',         'slug' => 'oud-sombre-nuit',
                'subtitle' => 'Parfum de Nuit Oriental',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'unisex','price' => 290.00, 'original_price' => null,
                'stock' => 20, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 43, 'brand_id' => 4, 'category_id' => 9,
                'name' => 'Trésor Midnight',         'slug' => 'tresor-midnight',
                'subtitle' => 'Parfum de Nuit Boisé',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 255.00, 'original_price' => 320.00,
                'stock' => 26, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 44, 'brand_id' => 6, 'category_id' => 9,
                'name' => 'Black Opium Nuit',        'slug' => 'black-opium-nuit',
                'subtitle' => 'Parfum de Nuit Gourmand',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 260.00, 'original_price' => null,
                'stock' => 30, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 45, 'brand_id' => 8, 'category_id' => 9,
                'name' => 'Ange ou Étrange',         'slug' => 'ange-ou-etrange',
                'subtitle' => 'Parfum de Nuit Mystérieux',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 215.00, 'original_price' => 270.00,
                'stock' => 22, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Category 10 — Coffret Cadeau (5 products)
            [
                'id' => 46, 'brand_id' => 3, 'category_id' => 10,
                'name' => 'Dior Prestige Set',       'slug' => 'dior-prestige-set',
                'subtitle' => 'Coffret Édition Limitée',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 520.00, 'original_price' => 650.00,
                'stock' => 15, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 47, 'brand_id' => 2, 'category_id' => 10,
                'name' => 'N°5 Precious Gift',       'slug' => 'n5-precious-gift',
                'subtitle' => 'Coffret Cadeau Signature',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 480.00, 'original_price' => 600.00,
                'stock' => 12, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 48, 'brand_id' => 1, 'category_id' => 10,
                'name' => 'Bloom Discovery Box',     'slug' => 'bloom-discovery-box',
                'subtitle' => 'Coffret Découverte',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'unisex','price' => 320.00, 'original_price' => 400.00,
                'stock' => 25, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 49, 'brand_id' => 4, 'category_id' => 10,
                'name' => 'Génifique Holiday Set',   'slug' => 'genifique-holiday-set',
                'subtitle' => 'Coffret Fêtes Luxe',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 420.00, 'original_price' => 520.00,
                'stock' => 18, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 50, 'brand_id' => 6, 'category_id' => 10,
                'name' => 'YSL Beauty Gift Set',     'slug' => 'ysl-beauty-gift-set',
                'subtitle' => 'Coffret Beauté',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 390.00, 'original_price' => 490.00,
                'stock' => 14, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Category 11 — Huile Parfumée (5 products)
            [
                'id' => 51, 'brand_id' => 1, 'category_id' => 11,
                'name' => 'Jasmine Silk Oil',        'slug' => 'jasmine-silk-oil',
                'subtitle' => 'Huile Corps Jasmin',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 145.00, 'original_price' => null,
                'stock' => 60, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 52, 'brand_id' => 1, 'category_id' => 11,
                'name' => "Rose d'Or Oil",           'slug' => 'rose-dor-oil',
                'subtitle' => 'Huile Précieuse à la Rose',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 155.00, 'original_price' => 195.00,
                'stock' => 50, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 53, 'brand_id' => 4, 'category_id' => 11,
                'name' => 'Arôme Précieux Oil',      'slug' => 'arome-precieux-oil',
                'subtitle' => 'Huile Parfumée Unisex',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'unisex','price' => 175.00, 'original_price' => null,
                'stock' => 40, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 54, 'brand_id' => 1, 'category_id' => 11,
                'name' => 'Cèdre Bloom Oil',         'slug' => 'cedre-bloom-oil',
                'subtitle' => 'Huile Boisée au Cèdre',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 140.00, 'original_price' => 180.00,
                'stock' => 55, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 55, 'brand_id' => 8, 'category_id' => 11,
                'name' => 'Vétiver Doré Oil',        'slug' => 'vetiver-dore-oil',
                'subtitle' => 'Huile Sèche au Vétiver',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'men',   'price' => 160.00, 'original_price' => null,
                'stock' => 42, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Category 12 — Gommage Corps (5 products)
            [
                'id' => 56, 'brand_id' => 1, 'category_id' => 12,
                'name' => 'Coffee Bloom Scrub',      'slug' => 'coffee-bloom-scrub',
                'subtitle' => 'Gommage au Café Bio',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'unisex','price' => 90.00,  'original_price' => 120.00,
                'stock' => 90, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 57, 'brand_id' => 1, 'category_id' => 12,
                'name' => 'Roses Pétales Scrub',     'slug' => 'roses-petales-scrub',
                'subtitle' => 'Gommage Doux aux Pétales',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 105.00, 'original_price' => null,
                'stock' => 70, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 58, 'brand_id' => 1, 'category_id' => 12,
                'name' => 'Citrus Exfoliant',        'slug' => 'citrus-exfoliant',
                'subtitle' => 'Exfoliant Énergisant Agrumes',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'unisex','price' => 80.00,  'original_price' => 100.00,
                'stock' => 85, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 59, 'brand_id' => 1, 'category_id' => 12,
                'name' => 'Argan Gommage',           'slug' => 'argan-gommage',
                'subtitle' => "Gommage Nourissant à l'Argan",
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'women', 'price' => 120.00, 'original_price' => 150.00,
                'stock' => 65, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 60, 'brand_id' => 1, 'category_id' => 12,
                'name' => 'Moroccan Sugar Scrub',    'slug' => 'moroccan-sugar-scrub',
                'subtitle' => 'Gommage Sucre du Maroc',
                'description' => $desc, 'ingredients' => $ingr,
                'gender' => 'unisex','price' => 95.00,  'original_price' => null,
                'stock' => 75, 'is_active' => true, 'is_featured' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
        ]);
    }
}
