<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('orders')->insert([
            // ── delivered ────────────────────────────────────────────────────
            [
                'id'                   => 1,
                'order_number'         => 'BL-TEST-001',
                'coupon_id'            => null,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Fatima Zahra',
                'customer_phone'       => '+212661001001',
                'customer_email'       => 'fz@test.ma',
                'shipping_address'     => '12 Rue Ibn Battouta',
                'shipping_city'        => 'Casablanca',
                'shipping_province'    => 'Casablanca-Settat',
                'shipping_postal_code' => '20000',
                'subtotal'             => 280.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 35.00,
                'total'                => 315.00,
                'status'               => 'delivered',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2025-12-01 09:00:00',
                'updated_at'           => '2025-12-04 10:30:00',
            ],
            [
                'id'                   => 2,
                'order_number'         => 'BL-TEST-002',
                'coupon_id'            => 1,
                'shipping_method_id'   => 2,
                'customer_name'        => 'Youssef Alami',
                'customer_phone'       => '+212662002002',
                'customer_email'       => null,
                'shipping_address'     => '45 Av Hassan II',
                'shipping_city'        => 'Rabat',
                'shipping_province'    => 'Rabat-Salé-Kénitra',
                'shipping_postal_code' => '10000',
                'subtotal'             => 420.00,
                'discount_amount'      => 42.00,
                'shipping_cost'        => 65.00,
                'total'                => 443.00,
                'status'               => 'shipped',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2025-12-03 14:00:00',
                'updated_at'           => '2025-12-04 17:00:00',
            ],
            [
                'id'                   => 3,
                'order_number'         => 'BL-TEST-003',
                'coupon_id'            => null,
                'shipping_method_id'   => 3,
                'customer_name'        => 'Nadia Benali',
                'customer_phone'       => '+212663003003',
                'customer_email'       => 'n.benali@mail.ma',
                'shipping_address'     => '8 Rue des Figuiers',
                'shipping_city'        => 'Marrakech',
                'shipping_province'    => 'Marrakech-Safi',
                'shipping_postal_code' => '40000',
                'subtotal'             => 550.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 0.00,
                'total'                => 550.00,
                'status'               => 'delivered',
                'notes'                => 'Livrer en matinée si possible',
                'admin_notes'          => null,
                'created_at'           => '2025-12-05 10:00:00',
                'updated_at'           => '2025-12-10 11:00:00',
            ],
            // ── processing ───────────────────────────────────────────────────
            [
                'id'                   => 4,
                'order_number'         => 'BL-TEST-004',
                'coupon_id'            => 2,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Karim Tahiri',
                'customer_phone'       => '+212664004004',
                'customer_email'       => null,
                'shipping_address'     => '77 Bd Mohammed V',
                'shipping_city'        => 'Fès',
                'shipping_province'    => 'Fès-Meknès',
                'shipping_postal_code' => '30000',
                'subtotal'             => 310.00,
                'discount_amount'      => 50.00,
                'shipping_cost'        => 35.00,
                'total'                => 295.00,
                'status'               => 'processing',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-20 08:00:00',
                'updated_at'           => '2026-02-22 09:00:00',
            ],
            // ── pending ───────────────────────────────────────────────────────
            [
                'id'                   => 5,
                'order_number'         => 'BL-TEST-005',
                'coupon_id'            => null,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Laila Ouahabi',
                'customer_phone'       => '+212665005005',
                'customer_email'       => null,
                'shipping_address'     => '3 Résidence Andalous',
                'shipping_city'        => 'Agadir',
                'shipping_province'    => 'Souss-Massa',
                'shipping_postal_code' => '80000',
                'subtotal'             => 140.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 35.00,
                'total'                => 175.00,
                'status'               => 'pending',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-25 07:00:00',
                'updated_at'           => '2026-02-25 07:00:00',
            ],
            // ── cancelled ─────────────────────────────────────────────────────
            [
                'id'                   => 6,
                'order_number'         => 'BL-TEST-006',
                'coupon_id'            => null,
                'shipping_method_id'   => 2,
                'customer_name'        => 'Omar Cherkaoui',
                'customer_phone'       => '+212666006006',
                'customer_email'       => null,
                'shipping_address'     => '21 Rue Al Khawarizmi',
                'shipping_city'        => 'Tanger',
                'shipping_province'    => 'Tanger-Tétouan-Al Hoceïma',
                'shipping_postal_code' => '90000',
                'subtotal'             => 260.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 65.00,
                'total'                => 325.00,
                'status'               => 'cancelled',
                'notes'                => null,
                'admin_notes'          => 'Annulé à la demande du client',
                'created_at'           => '2026-02-10 12:00:00',
                'updated_at'           => '2026-02-11 09:00:00',
            ],
            // ── confirmed ─────────────────────────────────────────────────────
            [
                'id'                   => 7,
                'order_number'         => 'BL-TEST-007',
                'coupon_id'            => 1,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Samira Idrissi',
                'customer_phone'       => '+212667007007',
                'customer_email'       => 's.idrissi@test.ma',
                'shipping_address'     => '9 Rue Imam Malik',
                'shipping_city'        => 'Meknès',
                'shipping_province'    => 'Fès-Meknès',
                'shipping_postal_code' => '50000',
                'subtotal'             => 390.00,
                'discount_amount'      => 39.00,
                'shipping_cost'        => 35.00,
                'total'                => 386.00,
                'status'               => 'confirmed',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-23 11:00:00',
                'updated_at'           => '2026-02-23 14:00:00',
            ],
            // ── shipped ───────────────────────────────────────────────────────
            [
                'id'                   => 8,
                'order_number'         => 'BL-TEST-008',
                'coupon_id'            => null,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Rachid Boussaid',
                'customer_phone'       => '+212668008008',
                'customer_email'       => null,
                'shipping_address'     => '14 Quartier Industriel',
                'shipping_city'        => 'Oujda',
                'shipping_province'    => 'Oriental',
                'shipping_postal_code' => '60000',
                'subtotal'             => 240.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 35.00,
                'total'                => 275.00,
                'status'               => 'shipped',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-18 09:00:00',
                'updated_at'           => '2026-02-20 15:00:00',
            ],
            // ── delivered ─────────────────────────────────────────────────────
            [
                'id'                   => 9,
                'order_number'         => 'BL-TEST-009',
                'coupon_id'            => null,
                'shipping_method_id'   => 3,
                'customer_name'        => 'Houda Mansouri',
                'customer_phone'       => '+212669009009',
                'customer_email'       => null,
                'shipping_address'     => '56 Hay El Fath',
                'shipping_city'        => 'Casablanca',
                'shipping_province'    => 'Casablanca-Settat',
                'shipping_postal_code' => '20200',
                'subtotal'             => 600.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 0.00,
                'total'                => 600.00,
                'status'               => 'delivered',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2025-12-15 10:00:00',
                'updated_at'           => '2025-12-20 14:00:00',
            ],
            // ── pending ───────────────────────────────────────────────────────
            [
                'id'                   => 10,
                'order_number'         => 'BL-TEST-010',
                'coupon_id'            => null,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Mehdi Saidi',
                'customer_phone'       => '+212670010010',
                'customer_email'       => null,
                'shipping_address'     => '2 Av des FAR',
                'shipping_city'        => 'Kenitra',
                'shipping_province'    => 'Rabat-Salé-Kénitra',
                'shipping_postal_code' => '14000',
                'subtotal'             => 120.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 35.00,
                'total'                => 155.00,
                'status'               => 'pending',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-25 06:00:00',
                'updated_at'           => '2026-02-25 06:00:00',
            ],
            // ── processing ───────────────────────────────────────────────────
            [
                'id'                   => 11,
                'order_number'         => 'BL-TEST-011',
                'coupon_id'            => null,
                'shipping_method_id'   => 2,
                'customer_name'        => 'Zineb Elmoutaouakil',
                'customer_phone'       => '+212671011011',
                'customer_email'       => null,
                'shipping_address'     => 'Boulevard Zerktouni Appt 5',
                'shipping_city'        => 'Casablanca',
                'shipping_province'    => 'Casablanca-Settat',
                'shipping_postal_code' => '20100',
                'subtotal'             => 310.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 65.00,
                'total'                => 375.00,
                'status'               => 'processing',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-22 08:00:00',
                'updated_at'           => '2026-02-24 09:00:00',
            ],
            // ── pending ───────────────────────────────────────────────────────
            [
                'id'                   => 12,
                'order_number'         => 'BL-TEST-012',
                'coupon_id'            => null,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Amine Belhaj',
                'customer_phone'       => '+212672012012',
                'customer_email'       => null,
                'shipping_address'     => '33 Résidence Al Amal',
                'shipping_city'        => 'Tétouan',
                'shipping_province'    => 'Tanger-Tétouan-Al Hoceïma',
                'shipping_postal_code' => '93000',
                'subtotal'             => 280.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 35.00,
                'total'                => 315.00,
                'status'               => 'pending',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-25 05:00:00',
                'updated_at'           => '2026-02-25 05:00:00',
            ],
            // ── confirmed ─────────────────────────────────────────────────────
            [
                'id'                   => 13,
                'order_number'         => 'BL-TEST-013',
                'coupon_id'            => null,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Sana Kettani',
                'customer_phone'       => '+212673013013',
                'customer_email'       => null,
                'shipping_address'     => '7 Rue du Commerce',
                'shipping_city'        => 'Safi',
                'shipping_province'    => 'Marrakech-Safi',
                'shipping_postal_code' => '46000',
                'subtotal'             => 140.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 35.00,
                'total'                => 175.00,
                'status'               => 'confirmed',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-24 11:00:00',
                'updated_at'           => '2026-02-24 15:00:00',
            ],
            // ── shipped ───────────────────────────────────────────────────────
            [
                'id'                   => 14,
                'order_number'         => 'BL-TEST-014',
                'coupon_id'            => null,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Hamid Lahlou',
                'customer_phone'       => '+212674014014',
                'customer_email'       => null,
                'shipping_address'     => '18 Hay Mohammadi',
                'shipping_city'        => 'Nador',
                'shipping_province'    => 'Oriental',
                'shipping_postal_code' => '62000',
                'subtotal'             => 390.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 35.00,
                'total'                => 425.00,
                'status'               => 'shipped',
                'notes'                => null,
                'admin_notes'          => null,
                'created_at'           => '2026-02-19 09:00:00',
                'updated_at'           => '2026-02-21 16:00:00',
            ],
            // ── cancelled ─────────────────────────────────────────────────────
            [
                'id'                   => 15,
                'order_number'         => 'BL-TEST-015',
                'coupon_id'            => null,
                'shipping_method_id'   => 1,
                'customer_name'        => 'Salma Benkirane',
                'customer_phone'       => '+212675015015',
                'customer_email'       => null,
                'shipping_address'     => '5 Allée des Roses',
                'shipping_city'        => 'El Jadida',
                'shipping_province'    => 'Casablanca-Settat',
                'shipping_postal_code' => '24000',
                'subtotal'             => 220.00,
                'discount_amount'      => 0.00,
                'shipping_cost'        => 35.00,
                'total'                => 255.00,
                'status'               => 'cancelled',
                'notes'                => null,
                'admin_notes'          => 'Client injoignable',
                'created_at'           => '2026-02-12 14:00:00',
                'updated_at'           => '2026-02-13 10:00:00',
            ],
        ]);
    }
}
